# no-op
name: GitHub Actions Demo
on:
  push:
    paths-ignore: .github
    branches: main
  pull_request_target:
    branches: main
  schedule:
    - cron: 15 6 * * SUN
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment type'     
        required: true
        default: 'Test'
  
jobs:
  build:
   runs-on: ubuntu-latest
   name: Build
   
   steps:
     - run: echo "${{ github.event_name }}"
     - uses: actions/checkout@v3
     - run: |
         echo "${{ github.repository }}"
         ls -R
         
  test:
    if: github.event_name == "workflow_dispatch"
    environment: Test
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Testing..."
  load-test:
    if: github.event_name == "workflow_dispatch"
    environment:  Load-Test
    needs: build
    runs-on: ubuntu-latest

    steps:
      - run: echo "Testing..."
      - run: sleep 15
  production:
    if: inputs.environment == "Production"
    needs: [test, load-test]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: "https://writeabout.net"

    steps:
      - run: for i in [1..5]; do echo "Step $i deploying for URL ${{ environment.url }}..." && sleep 10; done
