name: Reuse other workflow
on: [workflow_dispatch]
jobs:
  call-workflow:
    with:
      who-to-greet: paulo
    uses: ./.github/workflows/reusable.yml
  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - run: echo "${{ needs.call-workflow.outputs.current-time }}"
    
